### ISSUE TITLE
关于使用的问题

### ISSUE THREAD

**Issue by liekkas** [Jolking/springmvc-shiro-react-redux-restful-example#1]
您好Jolking。
目前碰到两个问题：

1. 不知道帐号密码。（虽然数据库有，但是是加密过后的，用Base64解码出现乱码）
2. 访问localhost:3000，随便输入登录帐号和密码，登录报404错误，访问不了http://localhost:3000/login.json，使用方式不对？这里的login.json是怎么来的？

我的操作方式：
1.npm start启动web端
2.mvn tomcat:run 启动后台

谢谢~

**Comment by Jolking** [comment]
你有没有进入到src/main/webapp目录下并执行 npm install && npm start这条命令呢？


项目运行成功以后 打开localhost:8080, 而不是直接访问localhost:3000/login.json, 因为main.html中引入js和css使用的是相对路径


如果不想运行java项目 只想打开前端那一部分的话
可以修改main.html
把bootstrap.min.css的href属性值修改为
http://localhost:3000/app/css/bootstrap.min.css
最下面有两个js脚本  
把原本没注释的注释掉
把原本注视掉的取消注视
再运行npm start  打开http://localhost:3000就可以看到登陆界面了
但是因为没有后台所以你没办法登陆 只能看到登录页面


一共有5个帐号:
数据库中有帐号 密码和帐号是一样的



login.json是登陆表单提交的地址  spring mvc 我设置了只处理 .json  .js  .css后缀的请求  所以需要以.json结尾




------------------ 原始邮件 ------------------
发件人: "Inclined.Z";<notifications@github.com>;
发送时间: 2016年4月24日(星期天) 下午3:20
收件人: "Jolking/springmvc-shiro-react-redux-restful-example"<springmvc-shiro-react-redux-restful-example@noreply.github.com>; 

主题: [Jolking/springmvc-shiro-react-redux-restful-example] 关于使用的问题 (#1)




您好Jolking。
 目前碰到两个问题：
  
不知道帐号密码。（虽然数据库有，但是是加密过后的，用Base64解码出现乱码）
 
访问localhost:3000，随便输入登录帐号和密码，登录报404错误，访问不了http://localhost:3000/login.json，使用方式不对？这里的login.json是怎么来的？
  
我的操作方式：
 1.npm start启动web端
 2.mvn tomcat:run 启动后台
 
谢谢~

**Comment by liekkas** [comment]
Hi @Jolking ，用你说的第二种方式打开前端没问题，可以看到登录界面。不过我想学习下整个流程。改用默认的设置。打开http://localhost:8080/不行，我加上了项目名称 http://localhost:8080/springmvc-shiro-react-redux-restful-example/，不过还是看不到界面，相关的js和css都加载不上，chrome控制台报
```
GET http://localhost:8080/springmvc-shiro-react-redux-restful-example/js/build/main.js 500 (Internal Server Error)
```
java端报错如下：
```
2016-04-24 21:56:42,559 [http-8080-1]  WARN [org.springframework.web.servlet.PageNotFound] - No mapping found for HTTP request with URI [/springmvc-shiro-react-redux-restful-example/app/js/build/main.js] in DispatcherServlet with name 'spring'

```
css也是如此，用的都是默认设置？有错过了什么吗？

**Comment by Jolking** [comment]
需要加上项目名是因为你和我的配置不同
如果你是用MyExlipse, 在工程目录上右键, 选properties, 弹出属性窗口, 选中MyEclipse－》Web, 在右边的Context root中修改保存即可.(应该是这样没错.. 太久没用了)
如果你用的是IDEA， 那么在Run/Debug Configurations中 tomcat server 页面， Deployment选项卡内的Application Context 设为 / 即可。

报这两个错可能是因为你和我的环境配置不同引起的， 你在项目根目录下执行
`mvn jetty:run`
试一试， 我在项目中有添加jetty的maven插件 运行成功后再次打开localhost:8080/

**Comment by liekkas** [comment]
hi, @Jolking ,我用的是Idea，按你所写一切OK，谢谢分享！

**Comment by Jolking** [comment]
@liekkas 项目很多地方写的不怎么样， 欢迎探讨
