### ISSUE TITLE
关于Shiro验证认证的问题

### ISSUE THREAD

**Issue by recwert** [Jolking/springmvc-shiro-react-redux-restful-example#2]
您好，我看您在生成用户密码的代码是：
`return new SimpleHash("md5", originStr, salt, 2).toHex();`

但是没看见您是如何设置Shiro也通过这种方式去验证密码，但是项目能够正常运行并且验证登陆
可以请教下您是在哪个地方进行配置了吗？

**Comment by Jolking** [comment]
`new SimpleHash("md5", originStr, salt, 2).toHex();`
这段代码的作用是对originStr进行加密
在测试目录下的UserServiceTest.java类中有创建用户的示例代码， 在对用户的密码进行加密后通过UserService.java的createUser方法将用户信息添加到数据库中。
在UserController.java类中有一个login方法， 在取出用户登陆传过来的账号和密码后调用了Subject的login方法去验证。
跟踪login方法的调用栈， 会发现最终调用了我们在shiro的配置文件中配置的MyRealm的doGetAuthenticationInfo方法， 在这个方法里我们从数据库中取出了数据库中的用户信息， 然后shiro会对我们数据库中的用户账号密码和用户传过来的账号密码进行对比。
我们在shiro的配置的配置
`<property name = "hashAlgorithmName" value = "md5"/>`
`<property name = "hashIterations" value = "2"/>`
`<property name = "storedCredentialsHexEncoded" value = "true"/>`
和new SimpleHash("md5", originStr, salt, 2).toHex();一样， 使用md5加密， 迭代2次， 并采用了hex编码， 所有shiro会对用户传过来的信息以同样的方式加密后验证登陆信息是否匹配。
